name: meetroom

services:
  backend:
    build: ./server-app
    ports:
      - "3000:3000"
    depends_on:
        - mediasoup
    restart: always  

    frontend:
      build: ./client-app
      ports:
        - "4200:80"
      depends_on:
        - backend
      restart: always
